INSERT INTO CUSTOMER
(CUSTOMER_ID, CITY, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET_NAME, STREET_NUMBER ) 
VALUES
(1001, 'TORONTO', 'CANADA', 'nitin.akash1989@gmail.com', 'NITIN', 'AKASH', '902-499-8927', 'M6C 3H3', 'ONTARIO', 'MARLEE AVE', 145);
INSERT INTO CUSTOMER
(CUSTOMER_ID, CITY, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET_NAME, STREET_NUMBER ) 
VALUES
(2001, 'HALIFAX', 'CANADA', 'nitin.akash2017@gmail.com', 'NITIN', 'AKASH', '647-561-2248', 'B3C T3T', 'NOVA SCOTIA', 'BRUNSWICK', 2309);
INSERT INTO CUSTOMER
(CUSTOMER_ID, CITY, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET_NAME, STREET_NUMBER ) 
VALUES
(3001, 'TORONTO', 'CANADA', 'kartikkuk@gmail.com', 'KARTIK', 'KARTIK', '902-897-4352', 'M6C 3H3', 'ONTARIO', 'MARLEE AVE', 145);
INSERT INTO CUSTOMER
(CUSTOMER_ID, CITY, COUNTRY, EMAIL, FIRST_NAME, LAST_NAME, PHONE_NUMBER, POSTAL_CODE, PROVINCE, STREET_NAME, STREET_NUMBER ) 
VALUES
(40001, 'SAINT JOHN', 'CANADA', 'prshob8@gmail.com', 'PRASHOB', 'NAIR', '905-487-8795', 'M6C 3H3', 'NEW BRUNSWICK', 'MAIN ROAD', 123);